### ISSUE TITLE
Connection failures between nodes and jenkins

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#109]
In the past couple of weeks we've seen an uptick in the number of connection issues between individual agent nodes and the Jenkins master.

These issues occur more frequently with specific hosts, mini2 is the most frequent exhibitor but icecube is now failing consistently and the issues appear on both portable and mini1 periodically as well.

I've been investigating the issue primarily with mini2 as it was "patient zero" and continues to be the most reliable machine to reproduce the failure, generally failing one in three builds. 

The failures are dirty, leaving behind stray processes and workspace files which can cause cascade failures on subsequent jobs (see #108 for one example). Below is an example stacktrace

<details>

```
FATAL: command execution failed
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:721)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Backing channel 'JNLP4-connect connection from 70-35-50-58.static.wiline.com/70.35.50.58:53560' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:212)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
	at com.sun.proxy.$Proxy67.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1138)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute shell' marked build as failure
FATAL: Remote call on JNLP4-connect connection from 70-35-50-58.static.wiline.com/70.35.50.58:53560 failed. The channel is closing down or has closed down
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:721)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: hudson.remoting.ChannelClosedException: Remote call on JNLP4-connect connection from 70-35-50-58.static.wiline.com/70.35.50.58:53560 failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:901)
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1053)
	at hudson.Launcher$ProcStarter.start(Launcher.java:450)
	at com.cloudbees.jenkins.plugins.sshagent.exec.ExecRemoteAgent.stop(ExecRemoteAgent.java:126)
	at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper$SSHAgentEnvironment.tearDown(SSHAgentBuildWrapper.java:417)
	at hudson.model.Build$BuildExecution.doRun(Build.java:174)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

</details>

I don't currently have a good handle on a root cause. Possible suspicions to investigate are are

* lack of memory allocated to the jenkins jvm to keep concurrent connections open
* Discrepancies in the remoting library version used by the swarm client versus the one used by the Jenkins instance. 

If I'm not able to resolve this by end of day the temporary solution is to revert back to using the direct JNLP agents in order to restore cluster health while investigating further.

**Comment by nuclearsandwich** [comment]
> Possible suspicions to investigate are are
> 
>  *  lack of memory allocated to the jenkins jvm to keep concurrent connections open

While most search results for exceptions in the above stacktrace are inconclusive, memory problems were mentioned in a different threads. The Jenkins JVM was still using the default starting and maximum heap sizes. 1/6 starting and 1/4 maximum physical memory for the JVM heap. ci.ros2.org has 15G physical memory so that would be 2.5G starting and 3.75G max heap, assuming the documentation is accurate. While Jenkins was being restarted to stop a runaway job on Windshield, I also
1. enabled garbage collection logging
2. Bumped starting and max heap to 4G and 10G. As this host is a dedicated jenkins server most of the memory should be available for jenkins-ing with some left by for the operating system and HTTPS proxy.

Since coming back online there have been no new instances of this issue but even mini2 would succeed for a couple builds before starting to fail so continued monitoring is required.

**Comment by nuclearsandwich** [comment]
### Brief Summary
Incident status: resolved
Issue description: Internet outage on site precipitated ongoing connection issues between on-site hosts and AWS Jenkins.
Resolution: Reboot of Jenkins host machine
Action items:
  * Update CI configuration branch with JNLP agent config.
  * Migrate hosts back to swarm client.
  * Monitor connectivity logs after connection is restored from future outages.
---

I was tucked into this issue for most of last week. After taking a step back and looking through the logs it looks like these issues started around the afternoon the office began experiencing connection issues. Even after connectivity was restored there were still frequent connection losses and timeouts between the Jenkins host and the in-office hosts.

In the IT spirit of turning things off and on again, the last thing to do was reboot the Jenkins host completely. Since doing so Thursday 2018-04-12T06:33 there have been no nightly jobs failed due to connectivity issues and the connection losses between the office and Jenkins hosts is back to the pre-incident frequency. Between @j-rivero and myself we aren't sure whether the issue was ultimately caused by bad network state on the jenkins host after the office connectivity outage or a resource leak ultimately resolved by rebooting the host instance. If the issue returns in the future running packet capture on both sides of the connection will help us identify any network trouble.

I think we can also absolve the swarm clients from any deleterious role in this issue as we encountered the same trouble with the same frequency after reverting to JNLP agents and the Linux swarm agents in AWS and ARM64 SSH agent in Packet.net were the only machines which did not suffer the issue at all.

Currently the in-building hosts are all running supervised JNLP agents. Since that's useful config to have I'll be updating the [configuration branch](https://github.com/ros2/ci/tree/configuration) of the CI repo with what is currently running. I don't think there's any great rush to return to the Swarm clients. I'll use the future PR to ros2ci to discuss the switch back.

**Comment by nuclearsandwich** [comment]
We experienced another spate of connection failures last night almost perfectly timed to within two hours of when I closed this issue.

new in round were connection issues with the linux hosts within AWS. Pointing to issues with the Jenkins host directly.

```
Apr 17, 2018 6:10:11 AM hudson.slaves.ChannelPinger$1 onDead
INFO: Ping failed. Terminating the channel JNLP4-connect connection from ip-172-30-0-9.ec2.internal/172.30.0.9:40234.
--
Apr 17, 2018 6:24:07 AM hudson.slaves.ChannelPinger$1 onDead
INFO: Ping failed. Terminating the channel JNLP4-connect connection from 108-90-40-133.lightspeed.sntcca.sbcglobal.net/108.90.40.133:51310.
--
Apr 17, 2018 6:57:22 PM hudson.slaves.ChannelPinger$1 onDead
INFO: Ping failed. Terminating the channel JNLP4-connect connection from ip-172-30-0-9.ec2.internal/172.30.0.9:59308.
--
Apr 17, 2018 11:45:16 PM hudson.slaves.ChannelPinger$1 onDead
INFO: Ping failed. Terminating the channel JNLP4-connect connection from ip-172-30-0-87.ec2.internal/172.30.0.87:54934
```

Looking at build failures
The first two to fail yesterday were
* https://ci.ros2.org/job/ci_linux/4241
* https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/1073
and both failed within a minute of each-other (timestamps UTC)

```
# ci_linux/4241
22:41:26 FATAL: remote file operation failed: /home/jenkins-agent/workspace/ci_linux@tmp/private_key_8620999780189834456.key at hudson.remoting.Channel@6feee0f2:JNLP4-connect connection from ip-172-30-0-9.ec2.internal/172.30.0.9:41512: hudson.remoting.ChannelClosedException: Remote call on JNLP4-connect connection from ip-172-30-0-9.ec2.internal/172.30.0.9:41512 failed. The channel is closing down or has closed down

# nightly_osx_repeated/1073
20:42:40 java.nio.channels.ClosedChannelException
```
It seems like build.osrfoundation.org is also experienced connection problems. The build https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/1475 failed though I don't see a way to get timestamps from that Jenkins instance.
