### ISSUE TITLE
icecube uses credential username after updates.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/build_farmer#115]
After today's updates. Running a test job on icecube was failing with ssh authentication errors. I checked the stuff from the setup notes and then generated a test key to make sure that key authentication works in general.

Upon closer examination I saw that it was using a strange username when trying to authenticate with github.com:
despite the git commands specifying `git@github.com` there is an authentication failure for `ros2-buildfarm@github.com: Permission denied (publickey)`. It turns out this username comes from the credential entry in the jenkins credential store. I've created a test credential using the same key but with the git@ username and that's allowing the test job to proceed.

I checked the Git 2.17 changelog for anything that would suggest this change from 2.16.2 but there was nothing that popped out. I don't have an easy way to see exactly what Jenkins is populating the environment variable with but we may need to switch the main credential username. 

<details><summary>Failure log</summary>

```
23:56:44 Building remotely on windows_icecube (test_windows) in workspace C:\J\workspace\testx_ci_win
23:57:06  > git rev-parse --is-inside-work-tree # timeout=10
23:57:07 Fetching changes from the remote Git repository
23:57:07  > git config remote.origin.url git@github.com:ros2/ci.git # timeout=10
23:57:07 Fetching upstream changes from git@github.com:ros2/ci.git
23:57:07  > git --version # timeout=10
23:57:07 using GIT_SSH to set credentials 
23:57:07  > git fetch --tags --progress git@github.com:ros2/ci.git +refs/heads/*:refs/remotes/origin/*
23:57:08 ERROR: Error fetching remote repo 'origin'
23:57:08 hudson.plugins.git.GitException: Failed to fetch from git@github.com:ros2/ci.git
23:57:08 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:862)
23:57:08 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1129)
23:57:08 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
23:57:08 	at hudson.scm.SCM.checkout(SCM.java:495)
23:57:08 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
23:57:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
23:57:08 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
23:57:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
23:57:08 	at hudson.model.Run.execute(Run.java:1724)
23:57:08 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
23:57:08 	at hudson.model.ResourceController.execute(ResourceController.java:97)
23:57:08 	at hudson.model.Executor.run(Executor.java:429)
23:57:08 Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress git@github.com:ros2/ci.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
23:57:08 stdout: 
23:57:08 stderr: ros2-buildfarm@github.com: Permission denied (publickey).
23:57:08 fatal: Could not read from remote repository.
23:57:08 
23:57:08 Please make sure you have the correct access rights
23:57:08 and the repository exists.
```

</details>

**Comment by nuclearsandwich** [comment]
I've confirmed that updating the credential username in Jenkins resolves the issue for updated hosts and does not hinder the ability for currently non-updated hosts to authenticate with GitHub. I'm not aware of anywhere that uses the SSH key credential with the username ros2-buildfarm and I think we can just rename the default credential.

**Comment by nuclearsandwich** [comment]
Updated the default credential name. If anyone notices authentication related failures in CI please report them here.
