### ISSUE TITLE
2018-06-07 Linux packaging jobs failed

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#123]
* https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/461/console
* https://ci.ros2.org/view/packaging/job/packaging_linux/1099/console

Both failed when trying to build the bridge with:

```
09:06:02 Traceback (most recent call last):
09:06:02   File "bin/ros1_bridge_generate_factories", line 11, in <module>
09:06:02     from ros1_bridge import generate_cpp
09:06:02   File "/home/rosbuild/ci_scripts/ws/src/ros2/ros1_bridge/ros1_bridge/__init__.py", line 21, in <module>
09:06:02     from ament_package import parse_package
09:06:02 ImportError: cannot import name 'parse_package'
```

**Comment by mikaelarguedas** [comment]
Fixed in https://github.com/ros2/ros1_bridge/pull/119
