### ISSUE TITLE
Windows repeated test_timer_number_callbacks100hertz mostly fails

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#139]
For the past week, the Windows repeated test of `test_timer_number_callbacks100hertz` has been failing in [CI](https://ci.ros2.org/view/nightly/job/nightly_win_rep/1132):

```
Error Message

AssertionError: should have received 4 callbacks, received [0, 1, 2]

Stacktrace

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\J\workspace\nightly_win_rep\ws\src\ros2\rclpy\rclpy\test\test_timer.py", line 29, in run_catch_report_raise
    return func(*args, **kwargs)
  File "C:\J\workspace\nightly_win_rep\ws\src\ros2\rclpy\rclpy\test\test_timer.py", line 79, in func_number_callbacks
    assert len(callbacks) == 4, 'should have received 4 callbacks, received %s' % str(callbacks)
AssertionError: should have received 4 callbacks, received [0, 1, 2]
"""

The above exception was the direct cause of the following exception:

    def test_timer_number_callbacks100hertz():
        func_launch(
>           func_number_callbacks, ['0.01'], "didn't receive the expected number of callbacks")

test\test_timer.py:167: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test\test_timer.py:136: in func_launch
    args=(function, args)
C:\Python36\lib\multiprocessing\pool.py:259: in apply
    return self.apply_async(func, args, kwds).get()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocessing.pool.ApplyResult object at 0x000002C7E7CA0D68>
timeout = None

    def get(self, timeout=None):
        self.wait(timeout)
        if not self.ready():
            raise TimeoutError
        if self._success:
            return self._value
        else:
>           raise self._value
E           AssertionError: should have received 4 callbacks, received [0, 1, 2]

C:\Python36\lib\multiprocessing\pool.py:644: AssertionError
```

**Comment by dhood** [comment]
1khz tests disabled in https://github.com/ros2/rclpy/pull/223. from discussion in https://github.com/ros2/rclcpp/issues/457 sounds like 100hz can be disabled too if it's still causing issues since the test isn't supposed to rely on hardware being fast enough

**Comment by clalancette** [comment]
As far as I can tell, this hasn't happened in at least the last week.  Thus, I'm going to close this out for now and we can reopen if we see the problem again.
