### ISSUE TITLE
Windows debug failed test_communications connext WStrings test

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#203]
Last night the Windows debug had a test failure in test_communication using connext with the WStrings test: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1257/testReport/junit/(root)/projectroot/test_publisher_subscriber__rclpy__rclcpp__rmw_connext_cpp/ .  It looks like this was between rclpy and rclcpp:

```

WARNING:test_publisher-23:'SIGINT' sent to process[test_publisher-23] not supported on Windows, escalating to 'SIGTERM'
[INFO] [test_publisher-23]: sending signal 'SIGTERM' to process[test_publisher-23]
INFO:test_publisher-23:sending signal 'SIGTERM' to process[test_publisher-23]
[ERROR] [test_publisher-23]: process has died [pid 9180, exit code 1, cmd 'C:\Python37\python_d.exe C:/J/workspace/nightly_win_deb/ws/src/ros2/system_tests/test_communication/test/publisher_py.py WStrings /test_time_10_08_05'].
ERROR:test_publisher-23:process has died [pid 9180, exit code 1, cmd 'C:\Python37\python_d.exe C:/J/workspace/nightly_win_deb/ws/src/ros2/system_tests/test_communication/test/publisher_py.py WStrings /test_time_10_08_05'].
test_processes_finished_gracefully[WStrings] (test_communication.TestPublisherSubscriberAfterShutdown)
Test that both executables finished gracefully. ... FAIL

======================================================================
FAIL: test_processes_finished_gracefully[WStrings] (test_communication.TestPublisherSubscriberAfterShutdown)
Test that both executables finished gracefully.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\J\workspace\nightly_win_deb\ws\build\test_communication\test_publisher_subscriber__rclpy__rclcpp__rmw_connext_cpp_Debug.py", line 77, in test_processes_finished_gracefully
    'test_subscriber'
  File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\launch_testing\asserts\assert_exit_codes.py", line 55, in assertExitCodes
    info.returncode
AssertionError: Proc test_subscriber-24 exited with code 1
```

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
