### ISSUE TITLE
Linux aarch64 repeated failed test_lifecycle

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#205]
It looks like Linux aarch64 repeated eventually failed test_lifecycle: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/789/#showFailuresLink

The error output seems to be:

```
1:  - ros2 test /home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/src/ros2/demos/lifecycle/test/test_lifecycle.py --junit-xml=/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/build/lifecycle/test_results/lifecycle/test_test_lifecycle.py.xunit.xml --package-name=lifecycle
1: [INFO] [launch]: All log files can be found below /home/rosbuild/.ros/log/2019-05-23-11-12-17-032046-c064d3b91445-33798
1: [INFO] [launch]: Default logging verbosity is set to INFO
1: test_talker_lifecycle (lifecycle.TestLifecyclePubSub)
1: Test lifecycle talker. ... [INFO] [lifecycle_talker-1]: process started with pid [33808]
1: [INFO] [lifecycle_listener-2]: process started with pid [33809]
1: [INFO] [lifecycle_listener-2]: sending signal 'SIGINT' to process[lifecycle_listener-2]
1: [INFO] [lifecycle_talker-1]: sending signal 'SIGINT' to process[lifecycle_talker-1]
1: [lifecycle_listener-2] [INFO] [rclcpp]: signal_handler(signal_value=2)
1: [lifecycle_talker-1] [INFO] [rclcpp]: signal_handler(signal_value=2)
1: [INFO] [lifecycle_listener-2]: process has finished cleanly [pid 33809]
1: [INFO] [lifecycle_talker-1]: process has finished cleanly [pid 33808]
1: ERROR
1: 
1: ======================================================================
1: ERROR: test_talker_lifecycle (lifecycle.TestLifecyclePubSub)
1: Test lifecycle talker.
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/src/ros2/demos/lifecycle/test/test_lifecycle.py", line 121, in test_talker_lifecycle
1:     proc_output.assertWaitFor('on_configure() is called', process=talker_node, timeout=5)
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/launch_testing/lib/python3.6/site-packages/launch_testing/io_handler.py", line 125, in assertWaitFor
1:     success = self.waitFor(*args, **kwargs)
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/launch_testing/lib/python3.6/site-packages/launch_testing/io_handler.py", line 172, in waitFor
1:     strict_proc_matching=False)
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/launch_testing/lib/python3.6/site-packages/launch_testing/util/proc_lookup.py", line 113, in resolveProcesses
1:     'No data recorded for proc {}'.format(_proc_to_name_and_args(process))
1: launch_testing.util.proc_lookup.NoMatchingProcessException: No data recorded for proc lifecycle_talker-1 __node:=lc_talker
1: 
1: ----------------------------------------------------------------------
1: Ran 1 test in 5.004s
1: 
1: FAILED (errors=1)
1: Future exception was never retrieved
1: future: <Future finished exception=InvalidHandle('Tried to use a handle that has been destroyed.',)>
1: Traceback (most recent call last):
1:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
1:     result = self.fn(*self.args, **self.kwargs)
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/launch_ros/lib/python3.6/site-packages/launch_ros/actions/lifecycle_node.py", line 78, in _call_change_state
1:     while not self.__rclpy_change_state_client.wait_for_service(timeout_sec=1.0):
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/rclpy/lib/python3.6/site-packages/rclpy/client.py", line 160, in wait_for_service
1:     while self.context.ok() and not self.service_is_ready() and timeout_sec > 0.0:
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/rclpy/lib/python3.6/site-packages/rclpy/client.py", line 143, in service_is_ready
1:     with self.handle as capsule:
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/rclpy/lib/python3.6/site-packages/rclpy/handle.py", line 146, in __enter__
1:     return self._get_capsule()
1:   File "/home/jenkins/workspace/nightly_linux-aarch64_repeated/ws/install/rclpy/lib/python3.6/site-packages/rclpy/handle.py", line 128, in _get_capsule
1:     raise InvalidHandle('Tried to use a handle that has been destroyed.')
1: rclpy.handle.InvalidHandle: Tried to use a handle that has been destroyed.
1: test_talker_graceful_shutdown (lifecycle.TestLifecyclePubSubAfterShutdown)
```

**Comment by clalancette** [comment]
This is still failing: https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/915

**Comment by clalancette** [comment]
We aren't using this repository anymore for buildfarm issues, so I'm going to archive it.  Thus I'm closing out this issue.  If you continue to have problems, please report another bug against https://github.com/ros2/ros2.  Thank you.
