### ISSUE TITLE
Windows debug failed rqt_graph tests

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#208]
In fact, it actually failed trying to even collect them, which is why it shows a red dot: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1259/

The real error that causes the failure is in rqt_graph tests, and looks like:
```
Starting >>> rqt_graph
c:\python37\lib\site-packages\setuptools\depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
running pytest
running egg_info
writing C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\rqt_graph.egg-info\PKG-INFO
writing dependency_links to C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\rqt_graph.egg-info\dependency_links.txt
writing entry points to C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\rqt_graph.egg-info\entry_points.txt
writing requirements to C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\rqt_graph.egg-info\requires.txt
writing top-level names to C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\rqt_graph.egg-info\top_level.txt
reading manifest file 'C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\rqt_graph.egg-info\SOURCES.txt'
writing manifest file 'C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\rqt_graph.egg-info\SOURCES.txt'
running build_ext
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
cachedir: C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\.pytest_cache
rootdir: C:\J\workspace\nightly_win_deb\ws\src\ros-visualization\rqt_graph
plugins: rerunfailures-7.0, repeat-0.8.0, cov-2.7.1
collected 0 items / 1 errors

=================================== ERRORS ====================================
____________________ ERROR collecting test/dotcode_test.py ____________________
ImportError while importing test module 'C:\J\workspace\nightly_win_deb\ws\src\ros-visualization\rqt_graph\test\dotcode_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test\dotcode_test.py:37: in <module>
    from rqt_graph.dotcode import RosGraphDotcodeGenerator
..\..\..\install\Lib\site-packages\rqt_graph\dotcode.py:38: in <module>
    from rqt_graph import rosgraph2_impl
..\..\..\install\Lib\site-packages\rqt_graph\rosgraph2_impl.py:53: in <module>
    from python_qt_binding.QtCore import qDebug, qWarning
..\..\..\install\Lib\site-packages\python_qt_binding\__init__.py:56: in <module>
    from python_qt_binding.binding_helper import loadUi  # noqa: F401
..\..\..\install\Lib\site-packages\python_qt_binding\binding_helper.py:279: in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
..\..\..\install\Lib\site-packages\python_qt_binding\binding_helper.py:120: in _select_qt_binding
    (', '.join(["'%s'" % b for b in binding_order]), '\n'.join(error_msgs)))
E   ImportError: Could not find Qt binding (looked for: 'pyqt', 'pyside'):
E     ImportError for 'pyqt': No module named 'PyQt5.QtCore'
E   Traceback (most recent call last):
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 108, in _select_qt_binding
E       QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 153, in _load_pyqt
E       _named_import('PyQt5.%s' % module_name)
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 133, in _named_import
E       module = builtins.__import__(name)
E   ModuleNotFoundError: No module named 'PyQt5.QtCore'
E   
E     ImportError for 'pyside': No module named 'PySide2'
E   Traceback (most recent call last):
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 108, in _select_qt_binding
E       QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 185, in _load_pyside
E       _named_import('PySide2.%s' % module_name)
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 133, in _named_import
E       module = builtins.__import__(name)
E   ModuleNotFoundError: No module named 'PySide2'
- generated xml file: C:\J\workspace\nightly_win_deb\ws\build\rqt_graph\pytest.xml -
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
```

**Comment by clalancette** [comment]
I see.  This is happening because https://github.com/ros2/ros2/pull/689 was merged last night.  PyQt5.QtCore is available for release mode on Windows, but not for debug.  I'll have to figure out how to add that.

**Comment by dirk-thomas** [comment]
I don't think there are debug builds of PySide available. I think we should simply skip the package on Windows debug builds.

**Comment by clalancette** [comment]
Just for future reference, I found this post which has some notes on how to build a debug version of PyQt5: https://www.riverbankcomputing.com/pipermail/pyqt/2012-April/031385.html
