### ISSUE TITLE
All nightlies failed last night

### ISSUE THREAD

**Issue by clalancette** [ros2/build_farmer#215]
On every platform, the nightlies failed the same way.  While trying to get the repository hashes via `vcstool`, they all got the following traceback:

```
# BEGIN SUBSECTION: repository hashes
==> vcs log -l1 "src"
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\vcs.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\vcstool\commands\vcs.py", line 26, in main
    return entrypoint(args)
  File "c:\python37\lib\site-packages\vcstool\commands\log.py", line 42, in main
    return simple_main(parser, LogCommand, args)
  File "c:\python37\lib\site-packages\vcstool\commands\command.py", line 90, in simple_main
    clients = find_repositories(command.paths, nested=command.nested)
  File "c:\python37\lib\site-packages\vcstool\crawler.py", line 10, in find_repositories
    _find_repositories(path, repos, visited, nested=nested)
  File "c:\python37\lib\site-packages\vcstool\crawler.py", line 15, in _find_repositories
    abs_path = os.path.abspath(path)
  File "c:\python37\lib\ntpath.py", line 526, in abspath
    return normpath(_getfullpathname(path))
TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not list
<== 'vcs log -l1 "src"' exited with return code '1'

C:\J\workspace\nightly_win_deb>echo "# END SECTION" 
"# END SECTION"
```

**Comment by dirk-thomas** [comment]
Addressed by `vcstool` 0.2.1
