### ISSUE TITLE
pytest hanging with pydocstyle 4.0.0

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#218]
There have been some jobs hanging on Linux and Linux aarch64:

```
ivanpauno [Today at 1:16 PM]
https://ci.ros2.org/job/ci_linux/7490/console too.
Strangely, both are hanging in `test/test_copyright.py` of `launch` package (edited)
12 replies

ivanpauno  [36 minutes ago]
https://ci.ros2.org/job/ci_linux/7492/console

ivanpauno  [36 minutes ago]
https://ci.ros2.org/job/ci_linux-aarch64/3630/console

ivanpauno  [36 minutes ago]
another two hanging in the same place

...

wjwwood  [12 minutes ago]
All the jobs on https://ci.ros2.org/computer/linux_aarch64_packet_net%202/ have frozen (three of them).

wjwwood  [12 minutes ago]
Since it spans packet.net and AWS, I’m guessing it either a Jenkins agent issue or a docker issue.

wjwwood  [10 minutes ago]
I changed the label to have an  `_offline` suffix, so new jobs won’t start on the packet machine, but without canceling the existing jobs so I can investigate.
```

**Comment by wjwwood** [comment]
On the packet.net machine, I saw that in `dmesg` some of the network adapters went into a disabled state:

```
root@ros2-ci-2:~# dmesg | tail -n 20
[1293052.903846] br-fa124eb77672: port 3(veth2d53f0e) entered forwarding state
[1293052.903879] br-fa124eb77672: port 3(veth2d53f0e) entered forwarding state
[1293067.949472] br-fa124eb77672: port 3(veth2d53f0e) entered forwarding state
[1294561.432484] br-fa124eb77672: port 3(veth2d53f0e) entered disabled state
[1294561.432734] veth02b1bc3: renamed from eth0
[1294561.506285] br-fa124eb77672: port 3(veth2d53f0e) entered disabled state
[1294561.515312] device veth2d53f0e left promiscuous mode
[1294561.515320] br-fa124eb77672: port 3(veth2d53f0e) entered disabled state
[1297477.484244] device vethbe5d2b8 entered promiscuous mode
[1297477.484612] IPv6: ADDRCONF(NETDEV_UP): vethbe5d2b8: link is not ready
[1297478.257856] eth0: renamed from veth33dcfdf
[1297478.285860] IPv6: ADDRCONF(NETDEV_CHANGE): vethbe5d2b8: link becomes ready
[1297478.286064] br-fa124eb77672: port 3(vethbe5d2b8) entered forwarding state
[1297478.286096] br-fa124eb77672: port 3(vethbe5d2b8) entered forwarding state
[1297493.336948] br-fa124eb77672: port 3(vethbe5d2b8) entered forwarding state
[1300872.007672] br-fa124eb77672: port 2(vetha0ff48e) entered disabled state
[1300872.007933] veth0e43a09: renamed from eth0
[1300872.048631] br-fa124eb77672: port 2(vetha0ff48e) entered disabled state
[1300872.057943] device vetha0ff48e left promiscuous mode
[1300872.057950] br-fa124eb77672: port 2(vetha0ff48e) entered disabled state
root@ros2-ci-2:~# python3 -c "import time; print(time.monotonic())"
1301193.330352778
root@ros2-ci-2:~# python3 -c "import time; print((time.monotonic() - 1300872.057950)/60)"
6.000425880115169
```

I was investigating around 6 minutes after we first noticed it, so it might be related. Perhaps, this hiccup prevented Jenkins from continuing to stream data, causing the hang? I don't know if this is a new problem or that a change in Jenkins now made it more sensitive to this kind of issue. Or maybe it's unrelated.

**Comment by wjwwood** [comment]
Hmm, one of the jobs was hung on archiving in one of the packaging jobs, and because of this I thought the job was not the issue (the other two stopped during the same test):

```
7.10.1. launch

Hide Details
Starting >>> launch
11:14:00 running pytest
11:14:00 running egg_info
11:14:00 writing /home/jenkins-agent/workspace/ci_linux/ws/build/launch/launch.egg-info/PKG-INFO
11:14:00 writing dependency_links to /home/jenkins-agent/workspace/ci_linux/ws/build/launch/launch.egg-info/dependency_links.txt
11:14:00 writing requirements to /home/jenkins-agent/workspace/ci_linux/ws/build/launch/launch.egg-info/requires.txt
11:14:00 writing top-level names to /home/jenkins-agent/workspace/ci_linux/ws/build/launch/launch.egg-info/top_level.txt
11:14:00 reading manifest file '/home/jenkins-agent/workspace/ci_linux/ws/build/launch/launch.egg-info/SOURCES.txt'
11:14:00 writing manifest file '/home/jenkins-agent/workspace/ci_linux/ws/build/launch/launch.egg-info/SOURCES.txt'
11:14:00 running build_ext
11:14:01 ============================= test session starts ==============================
11:14:01 platform linux -- Python 3.6.8, pytest-4.6.4, py-1.8.0, pluggy-0.12.0
11:14:01 cachedir: /home/jenkins-agent/workspace/ci_linux/ws/build/launch/.pytest_cache
11:14:01 rootdir: /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/launch/launch
11:14:01 plugins: cov-2.7.1, repeat-0.8.0, rerunfailures-7.0
11:14:01 collecting ... 
11:14:02 collecting 81 items                                                            
11:14:02 collected 142 items                                                            
11:14:02 
11:14:02 test/test_copyright.py .                                                 [  0%]
```

But since it appears two jobs stopped here and the packaging job finally continued (and since it's also on AWS machines for x86_64 Linux), I'm now thinking it's something in that test?

----

Also, I finally got an error from the console view of Jenkins in (https://ci.ros2.org/job/ci_linux/7492/consoleFull):

```

HTTP ERROR 403

Problem accessing /job/ci_linux/7492/logText/progressiveHtml. Reason:

    No valid crumb was included in the request

Powered by Jetty:// 9.4.z-SNAPSHOT
```

But that might be also unrelated or a symptom.

**Comment by wjwwood** [comment]
It looks like it's just stuck in pytest:

```
19874 jenkins    20   0 2578M 66764  8464 S  0.0  0.1  1:15.31 │  │  │     │  │     └─ /home/jenkins/workspace/ci_linux-aarch64/venv/bin/python /home/jenkins/workspace/ci_linux-aarch64/venv/bin/colcon test --base-paths src --build-base bu
22261 jenkins    20   0 2578M 66764  8464 S  0.0  0.1  0:00.00 │  │  │     │  │        ├─ /home/jenkins/workspace/ci_linux-aarch64/venv/bin/python /home/jenkins/workspace/ci_linux-aarch64/venv/bin/colcon test --base-paths src --build-base
22260 jenkins    20   0 2578M 66764  8464 S  0.0  0.1  0:00.00 │  │  │     │  │        ├─ /home/jenkins/workspace/ci_linux-aarch64/venv/bin/python /home/jenkins/workspace/ci_linux-aarch64/venv/bin/colcon test --base-paths src --build-base
22259 jenkins    20   0  266M 48332  8064 S  0.0  0.0  0:08.58 │  │  │     │  │        ├─ /home/jenkins/workspace/ci_linux-aarch64/venv/bin/python setup.py pytest egg_info --egg-base /home/jenkins/workspace/ci_linux-aarch64/ws/build/launc
22357 jenkins    20   0 52164 42420  3812 S  0.0  0.0  0:00.45 │  │  │     │  │        │  ├─ /home/jenkins/workspace/ci_linux-aarch64/venv/bin/python setup.py pytest egg_info --egg-base /home/jenkins/workspace/ci_linux-aarch64/ws/build/la
... repeated many times
```

**Comment by wjwwood** [comment]
It's stuck in `wait4`:

```
root@ros2-ci-2:~# strace -p 22259
strace: Process 22259 attached
wait4(22232,
```

Killing `pytest` didn't do anything, but killing `colcon test` gave:

```
10:19:54 
10:19:55 test/test_copyright.py .                                                 [  0%]

12:39:31 
12:39:31 II> colcon test returned: '-15'
12:39:31 # END SUBSECTION
12:39:31 
2. ccache stats (after)

Hide Details
# BEGIN SUBSECTION: ccache stats (after)
12:39:31 (venv)
12:39:31 ==> ccache -s
12:39:31 cache directory                     /home/rosbuild/.ccache
12:39:31 primary config                      /home/rosbuild/.ccache/ccache.conf
12:39:31 secondary config      (readonly)    /etc/ccache.conf
12:39:31 cache hit (direct)               8843877
12:39:31 cache hit (preprocessed)         2952815
12:39:31 cache miss                       2629764
12:39:31 cache hit rate                     81.77 %
12:39:31 called for link                  5408659
12:39:31 called for preprocessing            6034
12:39:31 compile failed                      9895
12:39:31 ccache internal error                  1
12:39:31 preprocessor error                 12889
12:39:31 cache file missing                    17
12:39:31 bad compiler arguments                42
12:39:31 autoconf compile/link               3106
12:39:31 no input file                       1925
12:39:31 cleanups performed                  1486
12:39:31 files in cache                     18300
12:39:31 cache size                           4.5 GB
12:39:31 max cache size                       5.0 GB
12:39:31 
12:39:31 # END SUBSECTION
12:39:31 Exception ignored in: <bound method BaseSubprocessTransport.__del__ of <_UnixSubprocessTransport closed pid=20640 returncode=-15 stdin=<_UnixWritePipeTransport closing fd=9 open>>>
12:39:31 Traceback (most recent call last):
12:39:31   File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 132, in __del__
12:39:31     self.close()
12:39:31   File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 106, in close
12:39:31     proto.pipe.close()
12:39:31   File "/usr/lib/python3.6/asyncio/unix_events.py", line 624, in close
12:39:31     self.write_eof()
12:39:31   File "/usr/lib/python3.6/asyncio/unix_events.py", line 610, in write_eof
12:39:31     self._loop.call_soon(self._call_connection_lost, None)
12:39:31   File "/usr/lib/python3.6/asyncio/base_events.py", line 591, in call_soon
12:39:31     self._check_closed()
12:39:31   File "/usr/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
12:39:31     raise RuntimeError('Event loop is closed')
12:39:31 RuntimeError: Event loop is closed

12:39:32 Build step 'Execute shell' marked build as failure
12:39:32 $ ssh-agent -k
12:39:32 unset SSH_AUTH_SOCK;
12:39:32 unset SSH_AGENT_PID;
12:39:32 echo Agent pid 82378 killed;
12:39:33 [ssh-agent] Stopped.
12:39:33 [WARNINGS] Skipping publisher since build result is FAILURE
12:39:33 [Cobertura] Publishing Cobertura coverage report...
12:39:33 
12:39:35 [xUnit] [INFO] - Starting to record.
12:39:35 [xUnit] [INFO] - Processing CTest-Version N/A (default)
12:39:35 [xUnit] [INFO] - [CTest-Version N/A (default)] - 1 test report file(s) were found with the pattern 'ws/build/*/Testing/*/Test.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'CTest-Version N/A (default)'.

12:39:35 [xUnit] [INFO] - Processing GoogleTest-1.6
12:39:36 [xUnit] [INFO] - [GoogleTest-1.6] - No test report file(s) were found with the pattern 'ws/build/*/test_results/**/*.gtest.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'GoogleTest-1.6'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'GoogleTest-1.6'?
12:39:36 [xUnit] [WARNING] - No test reports found for the metric 'GoogleTest' with the resolved pattern 'ws/build/*/test_results/**/*.gtest.xml'.
12:39:36 [xUnit] [INFO] - Skipping the metric tool processing.
12:39:36 [xUnit] [INFO] - Processing JUnit
12:39:36 [xUnit] [INFO] - [JUnit] - 15 test report file(s) were found with the pattern 'ws/build/*/pytest.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'JUnit'.
12:39:36 [xUnit] [INFO] - Processing JUnit
12:39:37 [xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern 'ws/build/*/test_results/**/*.xunit.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
12:39:37 [xUnit] [WARNING] - No test reports found for the metric 'JUnit' with the resolved pattern 'ws/build/*/test_results/**/*.xunit.xml'.
12:39:37 [xUnit] [INFO] - Skipping the metric tool processing.
12:39:37 [xUnit] [INFO] - Processing CTest-Version N/A (default)
12:39:37 [xUnit] [INFO] - [CTest-Version N/A (default)] - No test report file(s) were found with the pattern 'work space/build space/*/Testing/*/Test.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'CTest-Version N/A (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'CTest-Version N/A (default)'?
12:39:37 [xUnit] [WARNING] - No test reports found for the metric 'CTest' with the resolved pattern 'work space/build space/*/Testing/*/Test.xml'.
12:39:37 [xUnit] [INFO] - Skipping the metric tool processing.
12:39:37 [xUnit] [INFO] - Processing GoogleTest-1.6
12:39:37 [xUnit] [INFO] - [GoogleTest-1.6] - No test report file(s) were found with the pattern 'work space/build space/*/test_results/**/*.gtest.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'GoogleTest-1.6'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'GoogleTest-1.6'?
12:39:37 [xUnit] [WARNING] - No test reports found for the metric 'GoogleTest' with the resolved pattern 'work space/build space/*/test_results/**/*.gtest.xml'.
12:39:37 [xUnit] [INFO] - Skipping the metric tool processing.
12:39:37 [xUnit] [INFO] - Processing JUnit

12:39:37 [xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern 'work space/build space/*/pytest.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
12:39:37 [xUnit] [WARNING] - No test reports found for the metric 'JUnit' with the resolved pattern 'work space/build space/*/pytest.xml'.
12:39:37 [xUnit] [INFO] - Skipping the metric tool processing.
12:39:37 [xUnit] [INFO] - Processing JUnit
12:39:37 [xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern 'work space/build space/*/test_results/**/*.xunit.xml' relative to '/home/jenkins/workspace/ci_linux-aarch64' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
12:39:37 [xUnit] [WARNING] - No test reports found for the metric 'JUnit' with the resolved pattern 'work space/build space/*/test_results/**/*.xunit.xml'.
12:39:37 [xUnit] [INFO] - Skipping the metric tool processing.
12:39:38 [xUnit] [INFO] - Check 'Failed Tests' threshold.
12:39:38 [xUnit] [INFO] - The total number of tests for this category exceeds the specified 'unstable' threshold value.
12:39:38 [xUnit] [INFO] - Setting the build status to FAILURE
12:39:38 [xUnit] [INFO] - Stopping recording.
12:39:38 Finished: FAILURE
```

So it looks like it might be a Python or colcon bug? Perhaps excited by some other change.

**Comment by wjwwood** [comment]
I restarted your job @ivanpauno:

https://ci.ros2.org/job/ci_linux-aarch64/3631/

I don't think I fixed anything, but I killed it from the host (not via Jenkins). I'm guessing there's a good chance it hangs again.

**Comment by wjwwood** [comment]
I cannot log into the machine running https://ci.ros2.org/job/ci_linux/7492/ atm, so I aborted it via Jenkins, and rebuilt it: https://ci.ros2.org/job/ci_linux/7493/

**Comment by wjwwood** [comment]
I tried tweaking the pytest version back up to latest since we had it pinned, but that didn't change anything.

**Comment by wjwwood** [comment]
I believe this pr fixes the issue: https://github.com/ros2/ci/pull/313

Unless it is very flaky and I just got a lucky run in. I'm running another test to be sure it's fixed with master rather that just the launch pr's branch.

**Comment by dirk-thomas** [comment]
The actual reason for the problem is https://gitlab.com/pycqa/flake8-docstrings/issues/36. Unfortunately `pytest` doesn't just relay the error reported from `flake8` but seems to hang indefinitely.

We will need to wait for a fix in `flake8-docstrings` to be released (https://gitlab.com/pycqa/flake8-docstrings/merge_requests/15) until we can unpin `pydocstyle` again.
