### ISSUE TITLE
rqt_reconfigure fails to import PyQt5 in Windows Debug builds

### ISSUE THREAD

**Issue by cottsay** [ros2/build_farmer#231]
Example build: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=nightly_win_deb&build=1345)](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1345/)

The tests run successfully in the corresponding `Release` build. Only Windows appears to be affected.

Backtrace:
```
test\test_treenode_qstditem.py:37: in <module>
    from rqt_reconfigure.treenode_qstditem import TreenodeQstdItem
..\..\..\install\Lib\site-packages\rqt_reconfigure\treenode_qstditem.py:37: in <module>
    from python_qt_binding.QtCore import Qt
..\..\..\install\Lib\site-packages\python_qt_binding\__init__.py:56: in <module>
    from python_qt_binding.binding_helper import loadUi  # noqa: F401 
..\..\..\install\Lib\site-packages\python_qt_binding\binding_helper.py:279: in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
..\..\..\install\Lib\site-packages\python_qt_binding\binding_helper.py:120: in _select_qt_binding
    (', '.join(["'%s'" % b for b in binding_order]), '\n'.join(error_msgs)))
E   ImportError: Could not find Qt binding (looked for: 'pyqt', 'pyside'):
E     ImportError for 'pyqt': No module named 'PyQt5.QtCore'
E   Traceback (most recent call last):
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 108, in _select_qt_binding
E       QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 153, in _load_pyqt
E       _named_import('PyQt5.%s' % module_name) 
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 133, in _named_import
E       module = builtins.__import__(name)
E   ModuleNotFoundError: No module named 'PyQt5.QtCore'
E   
E     ImportError for 'pyside': No module named 'PySide2'
E   Traceback (most recent call last):
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 108, in _select_qt_binding
E       QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 185, in _load_pyside 
E       _named_import('PySide2.%s' % module_name) 
E     File "C:\J\workspace\nightly_win_deb\ws\install\Lib\site-packages\python_qt_binding\binding_helper.py", line 133, in _named_import
E       module = builtins.__import__(name)
E   ModuleNotFoundError: No module named 'PySide2'
```

**Comment by cottsay** [comment]
Should be addressed by ros2/ci#330.
