### ISSUE TITLE
MacOS Failures in venv/colcon

### ISSUE THREAD

**Issue by mjcarroll** [ros2/build_farmer#263]
All macOS CI builds are currently broken by an interaction with the virtualenv and colcon.

```
01:31:27 (venv)
01:31:27 ==> /Users/osrf/jenkins-agent/workspace/nightly_osx_release/venv/bin/colcon mixin remove default || true
01:31:28 Traceback (most recent call last):
01:31:28   File "/Users/osrf/jenkins-agent/workspace/nightly_osx_release/venv/bin/colcon", line 5, in <module>
01:31:28     from colcon_core.command import main
01:31:28 ModuleNotFoundError: No module named 'colcon_core'
01:31:28 
01:31:28 (venv)
01:31:28 ==> /Users/osrf/jenkins-agent/workspace/nightly_osx_release/venv/bin/colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
01:31:28 Traceback (most recent call last):
01:31:28   File "/Users/osrf/jenkins-agent/workspace/nightly_osx_release/venv/bin/colcon", line 5, in <module>
01:31:28     from colcon_core.command import main
01:31:28 ModuleNotFoundError: No module named 'colcon_core'
01:31:28 <== '. ../venv/bin/activate && /Users/osrf/jenkins-agent/workspace/nightly_osx_release/venv/bin/colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml' exited with return code '1'
01:31:28 Build step 'Execute shell' marked build as failure
```

**Comment by mjcarroll** [comment]
https://github.com/ros2/ci/pull/384

**Comment by mjcarroll** [comment]
Related: https://github.com/pypa/virtualenv/issues/1599

Indicates that this likely changed between 16.x and 20.x

**Comment by mjcarroll** [comment]
This was resolved by: https://github.com/ros2/ci/pull/385, macOS builds are now turning over.
