### ISSUE TITLE
looks like mini1 is not working

### ISSUE THREAD

**Issue by wjwwood** [ros2/build_farmer#53]
These two jobs failed:

- http://ci.ros2.org/job/ci_osx/2585/
- http://ci.ros2.org/job/ci_osx/2586/

So I took it off-line and started a new one. I don't have time to look into why it's failing atm.

**Comment by sloretz** [comment]
Output from the jenkins slave process

```
INFO: [xUnit] - [JUnit] - No test report file(s) were found with the pattern 'work space/build space/*/test_results/**/*.xunit.xml' relative to '/Users/osrf/jenkins/workspace/nightly_osx_repeated' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
Sep 18, 2017 7:34:42 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel channel
java.net.SocketException: Operation timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:114)
	at javax.crypto.CipherInputStream.read(CipherInputStream.java:192)
	at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:82)
	at hudson.remoting.ChunkedInputStream.readHeader(ChunkedInputStream.java:72)
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:103)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

Sep 18, 2017 7:34:42 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
Sep 18, 2017 7:34:57 PM hudson.remoting.Engine waitForServerToBack
INFO: Failed to connect to the master. Will retry again
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at hudson.remoting.Engine.waitForServerToBack(Engine.java:458)
	at hudson.remoting.Engine.run(Engine.java:356)

Sep 18, 2017 7:35:12 PM hudson.remoting.Engine waitForServerToBack
INFO: Failed to connect to the master. Will retry again
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at hudson.remoting.Engine.waitForServerToBack(Engine.java:458)
	at hudson.remoting.Engine.run(Engine.java:356)

Sep 18, 2017 7:35:22 PM jenkins.slaves.restarter.JnlpSlaveRestarterInstaller$2$1 onReconnect
INFO: Restarting agent via jenkins.slaves.restarter.UnixSlaveRestarter@623df203
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: osx_slave_mini1
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://ci.ros2.org/]
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to ci.ros2.org:58514
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP3-connect
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: JNLP3-connect: Incorrect challenge response from master
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to ci.ros2.org:58514
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP2-connect
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server didn't accept the handshake: 
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to ci.ros2.org:58514
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP-connect
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server didn't accept the handshake: Disabled protocol:Protocol:JNLP-connect
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to ci.ros2.org:58514
Sep 18, 2017 7:35:23 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:366)
	at hudson.remoting.Engine.run(Engine.java:338)

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]
```

**Comment by sloretz** [comment]
Not sure what caused the jenkins agent to crash, but it's connected after restarting it. If it stays connected for 20 minutes I'll bring it back online and close this under the assumption that it was a temporary issue.

**Comment by sloretz** [comment]
It stayed connected for 20min so I brought it online. It is now running http://ci.ros2.org/job/nightly_osx_debug/593/. I'll close when the job completes

**Comment by wjwwood** [comment]
Thanks for looking at it @sloretz, sorry I didn't have time to do it myself.
