### ISSUE TITLE
Installation step failed on windows

### ISSUE THREAD

**Issue by dhood** [ros2/build_farmer#97]
If I'm interpreting things correctly the build step for `test_rclcpp` was fine but it had issues with the installation.

Key output:
https://ci.ros2.org/view/nightly/job/nightly_win_rep/1013/consoleFull
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
...

'['c:\\J\\workspace\\nightly_win_rep\\ws\\build\\test_rclcpp\\cmake__install.bat', 'C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.EXE', '/p:Configuration=Release', 'c:\\J\\workspace\\nightly_win_rep\\ws\\build\\test_rclcpp\\INSTALL.vcxproj']' returned non-zero exit status 3221225477
```

Icecube successfully completed https://ci.ros2.org/job/packaging_windows/941/ since then. The history lists this as the first known build because the agent's name has changed.

Full output:
```
Done Building Project "C:\J\workspace\nightly_win_rep\ws\build\test_rclcpp\gtest_timeout_subscriber__rmw_fastrtps_cpp.vcxproj" (default targets).

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Text.StringBuilder.ToString()
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Microsoft.Build.Evaluation.Expander`2.MetadataExpander.ExpandMetadataLeaveEscaped(String expression, IMetadataTable metadata, ExpanderOptions options)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemElement(Boolean itemGroupConditionResult, ProjectItemElement itemElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemGroupElement(ProjectItemGroupElement itemGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.BackEnd.RequestBuilder.LoadProjectIntoConfiguration()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean setThreadParameters)
   at Microsoft.Build.BackEnd.RequestBuilder.<StartBuilderThread>b__44_2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
  add_diagnostics__type_support.cpp
  Path_Support.cxx
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    SECURITY


-- Build files have been written to: C:/J/workspace/nightly_win_rep/ws/build/test_communication
==> 'c:\J\workspace\nightly_win_rep\ws\build\test_communication\cmake__build.bat C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.EXE /m:4 /p:Configuration=Release c:\J\workspace\nightly_win_rep\ws\build\test_communication\test_communication.sln' in 'c:\J\workspace\nightly_win_rep\ws\build\test_communication'
  self_test__request__type_support.cpp
  grid_cells__type_support.cpp
"NDDSHOME changed from \"C:\Program Files\rti_connext_dds-5.3.0\" to \"C:/Program Files/rti_connext_dds-5.3.0\"" 
  self_test__response__type_support.cpp
  map_meta_data__type_support.cpp

<== Command 'c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp\cmake__install.bat C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.EXE /p:Configuration=Release c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp\INSTALL.vcxproj' failed in 'c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp' with exit code '3221225477'
SystemExit in test_rclcpp: <== Command 'c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp\cmake__install.bat C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.EXE /p:Configuration=Release c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp\INSTALL.vcxproj' failed in 'c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp' with exit code '3221225477'
Traceback (most recent call last):
  File "c:\J\workspace\nightly_win_rep\ws\src\ament\ament_tools\ament_tools\verbs\build_pkg\cli.py", line 253, in run_command
    subprocess.check_call(cmd, shell=True, cwd=cwd, env=build_action.env)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\J\\workspace\\nightly_win_rep\\ws\\build\\test_rclcpp\\cmake__install.bat', 'C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.EXE', '/p:Configuration=Release', 'c:\\J\\workspace\\nightly_win_rep\\ws\\build\\test_rclcpp\\INSTALL.vcxproj']' returned non-zero exit status 3221225477.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\J\workspace\nightly_win_rep\ws\src\ament\ament_tools\ament_tools\verbs\build\cli.py", line 384, in process_in_parallel
    result = done_future.result()
  File "C:\Python36\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\J\workspace\nightly_win_rep\ws\src\ament\ament_tools\ament_tools\verbs\build_pkg\cli.py", line 280, in main
    return run(opts, context)
  File "c:\J\workspace\nightly_win_rep\ws\src\ament\ament_tools\ament_tools\verbs\build_pkg\cli.py", line 338, in run
    handle_build_action(on_install_ret, context)
  File "c:\J\workspace\nightly_win_rep\ws\src\ament\ament_tools\ament_tools\verbs\build_pkg\cli.py", line 270, in handle_build_action
    run_command(build_action, context)
  File "c:\J\workspace\nightly_win_rep\ws\src\ament\ament_tools\ament_tools\verbs\build_pkg\cli.py", line 262, in run_command
    sys.exit(msg)
SystemExit: <== Command 'c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp\cmake__install.bat C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.EXE /p:Configuration=Release c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp\INSTALL.vcxproj' failed in 'c:\J\workspace\nightly_win_rep\ws\build\test_rclcpp' with exit code '3221225477'
  self_test__type_support.cpp
```

**Comment by clalancette** [comment]
It looks like https://ci.ros2.org/view/nightly/job/nightly_win_rep/ has been fine for going on 3 weeks now, so I'm going to close this out.  Feel free to reopen if we see this again or other action needs to be taken.
